config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :oenologists
  resources :job_titles
  resources :magazines
  resources :wine_strains
  resources :strains
  resources :wines

  root to: "wines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job_title.rb
class JobTitle < ApplicationRecord
    has_many :oenologistmagazinejobs, dependent: :destroy
    has_many :magazines, through: :oenologistmagazinejobs, dependent: :destroy
    has_many :oenologists, through: :oenologistmagazinejobs, dependent: :destroy
end

app/controllers/job_titles_controller.rb
class JobTitlesController < ApplicationController
  before_action :authorize_admin!, except: [:index] 
  before_action :set_job_title, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin!

  # GET /job_titles
  # GET /job_titles.json
  def index
    @job_titles = JobTitle.all
  end

  # GET /job_titles/1
  # GET /job_titles/1.json
  def show
  end

  # GET /job_titles/new
  def new
    @job_title = JobTitle.new
  end

  # GET /job_titles/1/edit
  def edit
  end

  # POST /job_titles
  # POST /job_titles.json
  def create
    @job_title = JobTitle.new(job_title_params)

    respond_to do |format|
      if @job_title.save
        format.html { redirect_to @job_title, notice: 'Job title was successfully created.' }
        format.json { render :show, status: :created, location: @job_title }
      else
        format.html { render :new }
        format.json { render json: @job_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_titles/1
  # PATCH/PUT /job_titles/1.json
  def update
    respond_to do |format|
      if @job_title.update(job_title_params)
        format.html { redirect_to @job_title, notice: 'Job title was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_title }
      else
        format.html { render :edit }
        format.json { render json: @job_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_titles/1
  # DELETE /job_titles/1.json
  def destroy
    @job_title.destroy
    respond_to do |format|
      format.html { redirect_to job_titles_url, notice: 'Job title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_title
      @job_title = JobTitle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_title_params
      params.require(:job_title).permit(:name)
    end
end

app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

app/views/job_titles/_form.html.erb
<%= form_with(model: job_title, local: true) do |form| %>
  <% if job_title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_title.errors.count, "error") %> prohibited this job_title from being saved:</h2>

      <ul>
      <% job_title.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/job_titles/edit.html.erb
<h1>Editing Job Title</h1>

<%= render 'form', job_title: @job_title %>

<%= link_to 'Show', @job_title %> |
<%= link_to 'Back', job_titles_path %>

app/views/job_titles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Job Titles</h1>

<table border=1>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_titles.each do |job_title| %>
      <tr>
        <td><%= job_title.name %></td>
        <td><%= link_to 'Show', job_title %></td>
        <td><%= link_to 'Edit', edit_job_title_path(job_title) %></td>
        <td><%= link_to 'Destroy', job_title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job Title', new_job_title_path %>

app/views/job_titles/new.html.erb
<h1>New Job Title</h1>

<%= render 'form', job_title: @job_title %>

<%= link_to 'Back', job_titles_path %>

app/views/job_titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @job_title.name %>
</p>

<%= link_to 'Edit', edit_job_title_path(@job_title) %> |
<%= link_to 'Back', job_titles_path %>